CREATE OR REPLACE VIEW HLIST
AS
SELECT ROWNUM RNUM, HEARTNO, JOBNO, USERNO
FROM (SELECT HEARTNO, JOBNO, USERNO
		FROM HEART H
		JOIN JOBSEARCH J ON(J.JOBNO = H.JOBNO)
		JOIN MEMBER M ON (M.USERNO = J.USERNO)
		ORDER BY 1 DESC);